//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int id { get; set; }
        public Nullable<int> customer { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> angle { get; set; }
        public Nullable<int> colour { get; set; }
        public Nullable<int> size { get; set; }
        public byte[] photo { get; set; }
        public string price { get; set; }
    
        public virtual Angle Angle1 { get; set; }
        public virtual Colour Colour1 { get; set; }
        public virtual Customer Customer1 { get; set; }
        public virtual Size Size1 { get; set; }
    }
}
